# Generated by Django 5.1.6 on 2025-03-28 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='stug',
            new_name='slug',
        ),
        migrations.RemoveField(
            model_name='actors',
            name='brith_date',
        ),
        migrations.AddField(
            model_name='actors',
            name='birth_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
